//The sequence of triangle numbers is generated by adding the natural numbers. So the7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.The first ten terms would be:
//1, 3, 6, 10, 15, 21, 28,36, 45, 55, ...
//Let us list the factors of the first seven triangle numbers:
//1: 1
//3: 1,3
//6: 1,2,3,6
//10: 1,2,5,10
//15: 1,3,5,15
//21: 1,3,7,21
//28: 1,2,4,7,14,28
//We can see that 28 is the first triangle number to have over five divisors.
//What is the value of the first triangle number to have over five hundred divisors?

//Answer: 76576500

namespace Program
{
    public class TriangleNumbers
    {
        public static void Main()
        {
            long triNum = 0;
            int i = 0;

            while(true)
            {
                i += 1;

                triNum += i;

                long divisors = GetDivisors(triNum);

                if (divisors > 500)
                {
                    Console.WriteLine($"The first triangle number to have over five hundred divisors is: {triNum}");
                    break;
                }
            }

            Console.ReadKey();
        }

        public static long GetDivisors(long triNum)
        {
            long divisors = 0;

            long limit = (long)Math.Sqrt(triNum);

            for (int i = 1; i <= limit; i++)
            {
                if (triNum % i == 0)
                {
                    divisors++;

                    if (i != (triNum / i))
                    {
                        if (i * i != triNum)
                            divisors++;
                    }
                }
            }

            return divisors;
        }
    }
}